version: '3.9'
services:
  api_ml_vocabulokid:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./models:/app/models  # for finetuned tesseract model
    networks:
      - shared_ml_network

networks:
  shared_ml_network:
    external: true