version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MODEL_PATH_PREFIX=/app/models
    volumes:
      - ./models:/app/models  # for storing ML models
    networks:
      - shared_ml_network

networks:
  shared_ml_network:
    external: true