const csvData = `

mot,categorie_grammaticale,definition,url_video_definition,url_video_mot,url_source
avoir,n.m.,ce que l'on a; ses biens.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/28_avoir_2__nm_1td001-encoded.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/avoir_nm_1_1.mp4,https://dico.elix-lsf.fr/dictionnaire/avoir/n.m.-134124
a priori,adj.,"d'une façon abstraite, non fondée sur les faits.",https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/apriori_adj_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/a%20priori/adj.-125237
a priori,adv.,au premier abord.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/apriori_adv_1.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/apriori_adv_1_2.mp4,https://dico.elix-lsf.fr/dictionnaire/a%20priori/adv.-125239
a priori,adv.,"à première vue, de prime abord.",https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/apriori_adv_2.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/apriori_adv_2_1.mp4,https://dico.elix-lsf.fr/dictionnaire/a%20priori/adv.-125240
a priori,n.m.,opinion qui ne tient pas compte de l'observation du réel.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/apriori_nm_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/a%20priori/n.m.-125238
abandon,n.m.,"action de laisser quelque chose, de renoncer à quelque chose.",https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandon_nm_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abandon/n.m.-125347
abandon,n.m.,action de quitter.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandon_nm_2.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandon_nm_2_6.mp4,https://dico.elix-lsf.fr/dictionnaire/abandon/n.m.-125348
abandon,n.m.,action de se laisser aller.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandon_nm_3.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandon_nm_3_11.mp4,https://dico.elix-lsf.fr/dictionnaire/abandon/n.m.-125349
abandon,n.m.,action de délaisser.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandon_nm_4.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandon_nm_4_1.mp4,https://dico.elix-lsf.fr/dictionnaire/abandon/n.m.-125350
abandon scolaire,n.,"S'applique à la situation des élèves ou des étudiants qui par incapacité, par manque de moyens financiers, etc., ne vont pas jusqu'au bout de la période d'études en cours.",https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandonscolaire_n_1.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandonscolaire_n_1_11.mp4,https://dico.elix-lsf.fr/dictionnaire/abandon%20scolaire/n.-125351
abandonnataire,n.m.,bénéficiaire d'un abandon de biens.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandonnataire_nm_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abandonnataire/n.m.-125352
abandonnateur,n.m.,personne qui abandonne ses biens.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandonnateur_nm_1.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandonnateur_nm_1_1.mp4,https://dico.elix-lsf.fr/dictionnaire/abandonnateur/n.m.-125353
abandonner,v.,"ne plus vouloir de quelque chose, renoncer à, délaisser, laisser définitivement.",https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/84_abandonner_1__v_1td001-encoded.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandonner_v_1_1.mp4,https://dico.elix-lsf.fr/dictionnaire/abandonner/v.-125356
abandonner,v.,"ne plus occuper, quitter.",https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/85_abandonner_1__v_2td001-encoded.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandonner_v_2_1.mp4,https://dico.elix-lsf.fr/dictionnaire/abandonner/v.-125357
abandonner,v.,interrompre une action en cours.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/86_abandonner_1__v_3td001-encoded.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abandonner_v_3_1.mp4,https://dico.elix-lsf.fr/dictionnaire/abandonner/v.-125358
abbesse,n.f.,supérieure d'un couvent érigé en abbaye.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abbesse_nf_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abbesse/n.f.-125447
abbé,n.m.,moine supérieur de l'Eglise grecque.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/1_abbe_1__nm_1td001.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abbe_nm_1_1_6.mp4,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9/n.m.-125433
abbé,n.m.,supérieur d'un monastère érigé en abbaye.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/1_abbe_1__nm_2td_ddy001-encoded.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abbe_nm_2_1.mp4,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9/n.m.-125434
abbevillien,adj. et n.,"période du paléolithique inférieur, caractérisé par des silex taillés sur les deux faces (biface).",Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abbevillien/adj.%20et%20n.-125449
abbréviation,Faute Ortho,"mauvaise orthographe couramment utilisée pour le mot ""abréviation""",Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abbr%C3%A9viation/Faute%20Ortho-125450
abbé Charles François Lhomond,n.prop.,"grammairien et éducateur français; auteur d'ouvrages destinés aux premières études de latin: De viris illustribus urbis Romo (vers 1775), Éléments de la grammaire latine (1779), etc.",Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9%20Charles%20Fran%C3%A7ois%20Lhomond/n.prop.-125435
abbé Edme Mariotte,n.,physicien français.,Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9%20Edme%20Mariotte/n.-125440
abbé Fulbert Youlou,n.,premier président de la république du Congo (1960-1963).,Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9%20Fulbert%20Youlou/n.-125441
abbé Henri Bremond,n.,critique littéraire et historien mystique français.,Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9%20Henri%20Bremond/n.-125442
abbé Henri Breuil,n.,préhistorien et paléontologue français.,Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9%20Henri%20Breuil/n.-125443
abbé Jean Picard,n.,astronome français.,Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9%20Jean%20Picard/n.-125445
abbé Jean-Jacques Barthélemy,n.,"écrivain français. ""Le Voyage du jeune Anacharsis en Grèce au IVe siècle de l'ère vulgaire"".",Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9%20Jean-Jacques%20Barth%C3%A9lemy/n.-125444
abbé René Just Haüy,n.prop.,"minéralogiste français, créateur de la cristallographie.",Non spécifié,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abb%C3%A9%20Ren%C3%A9%20Just%20Ha%C3%BCy/n.prop.-125446
abeillage,n.m.,droit seigneurial sur les ruches de leurs vassaux.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abeillage_nm_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abeillage/n.m.-125493
abeille,n.f.,insecte social hyménoptère produisant le miel et la cire.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/13_abeille_1__nf_1td001-encoded.mp4,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abeille_nf_1_1.mp4,https://dico.elix-lsf.fr/dictionnaire/abeille/n.f.-125494
abeille charpentière,n.f.,abeille tropicale qui creuse des galeries dans le bois mort pour y pondre.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abeillecharpentiere_nf_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abeille%20charpenti%C3%A8re/n.f.-125495
abeille maçonne,n.f.,abeille solitaire.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abeillemaconne_nf_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abeille%20ma%C3%A7onne/n.f.-125496
abeille menuisière,n.f.,abeille tropicale qui creuse des galeries dans le bois mort pour y pondre.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abeillemenuisiere_nf_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abeille%20menuisi%C3%A8re/n.f.-125497
abeille ouvrière,n.f.,"abeille stérile d'une ruche, ou fourmi et guêpe neutres.",https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abeilleouvriere_nf_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abeille%20ouvri%C3%A8re/n.f.-125498
abeille travailleuse,n.,"abeille stérile d'une ruche, ou fourmi et guêpe neutres.",https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abeilletravailleuse_n_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abeille%20travailleuse/n.-125499
abeille ventileuse,n.f.,abeille qui assure l'aération d'une ruche en battant ses ailes.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abeilleventileuse_nf_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abeille%20ventileuse/n.f.-125500
b,n.f.,abeille qui assure l'aération d'une ruche en battant ses ailes.,https://elix-lsf.s3.rbx.io.cloud.ovh.net/spip_videos/abeilleventileuse_nf_1.mp4,Non spécifié,https://dico.elix-lsf.fr/dictionnaire/abeille%20ventileuse/n.f.-125500`;

export default csvData;